#!/usr/bin/env bash
# Bootstrap ~/.devproxy/ for codelabs-dev-servers plugin.
set -euo pipefail

DEVPROXY_HOME="${DEVPROXY_HOME:-$HOME/.devproxy}"

mkdir -p "$DEVPROXY_HOME/config" "$DEVPROXY_HOME/certs"

if [[ ! -f "$DEVPROXY_HOME/config/routes.json" ]]; then
    cat > "$DEVPROXY_HOME/config/routes.json" <<'EOF'
{
  "version": 1,
  "routes": [],
  "updated_at": "1970-01-01T00:00:00Z"
}
EOF
    echo "  routes.json: created"
fi

# Generate empty Caddyfile
cat > "$DEVPROXY_HOME/Caddyfile" <<'EOF'
{
    # Auto-generated by codelabs-dev-servers
    local_certs
    admin localhost:2019
    log {
        level WARN
    }
}

# No routes configured yet. Use codelabs-dev-servers plugin to add some.
EOF

echo "✅ ~/.devproxy/ bootstrapped at $DEVPROXY_HOME"
